#!/usr/bin/env python3
"""Build a standalone 6-DOF PiperX dynamics URDF with the official gripper.

The upstream gripper description is a Xacro file that depends on a ROS package
layout and adds three prismatic gripper joints.  The impedance controllers only
command the six arm joints, so this script:

1. merges the upstream PiperX arm and gripper descriptions;
2. locks the gripper joints at their zero position while retaining inertia;
3. removes visual/collision meshes (not needed for dynamics);
4. adds a configurable fixed ``tcp_link`` under ``gripper_base``.
"""

from __future__ import annotations

import argparse
import copy
from pathlib import Path
import xml.etree.ElementTree as ET


PROJECT_ROOT = Path(__file__).resolve().parents[1]
UPSTREAM_ROOT = PROJECT_ROOT / "third_party" / "agx_arm_urdf"
DEFAULT_ARM_URDF = UPSTREAM_ROOT / "piper_x" / "urdf" / "piper_x_description.urdf"
DEFAULT_GRIPPER_XACRO = (
    UPSTREAM_ROOT / "piper_x" / "urdf" / "piper_x_with_gripper_description.xacro"
)
DEFAULT_OUTPUT = PROJECT_ROOT / "piper_x" / "urdf" / "piper_x_with_gripper_tcp.urdf"
GRIPPER_JOINTS = {"gripper", "gripper_joint1", "gripper_joint2"}


def _vec3(values: list[float]) -> str:
    if len(values) != 3:
        raise ValueError("TCP xyz/rpy must contain exactly three values")
    return " ".join(f"{value:.9g}" for value in values)


def build_model(
    arm_urdf: Path,
    gripper_xacro: Path,
    output: Path,
    tcp_xyz: list[float],
    tcp_rpy: list[float],
) -> None:
    arm_root = ET.parse(arm_urdf).getroot()
    gripper_root = ET.parse(gripper_xacro).getroot()

    if arm_root.tag != "robot" or arm_root.get("name") != "piper_x":
        raise ValueError(f"Unexpected PiperX arm model: {arm_urdf}")
    if gripper_root.tag != "robot" or gripper_root.get("name") != "piper_x":
        raise ValueError(f"Unexpected PiperX gripper model: {gripper_xacro}")

    existing_names = {
        (element.tag, element.get("name"))
        for element in arm_root
        if element.get("name") is not None
    }
    for element in gripper_root:
        # The only namespaced element is xacro:include; the base arm is already
        # loaded above.
        if element.tag.startswith("{"):
            continue
        key = (element.tag, element.get("name"))
        if key in existing_names:
            continue
        arm_root.append(copy.deepcopy(element))
        existing_names.add(key)

    # Keep this model independent of ROS package/mesh lookup. Pinocchio only
    # needs links, joints, and inertial properties for the controllers.
    for link in arm_root.findall("link"):
        for tag in ("visual", "collision"):
            for child in list(link.findall(tag)):
                link.remove(child)

    # The physical gripper remains independently controlled. Locking these
    # model joints preserves all child inertias while keeping nq=nv=6.
    for joint in arm_root.findall("joint"):
        if joint.get("name") not in GRIPPER_JOINTS:
            continue
        joint.set("type", "fixed")
        for tag in ("axis", "limit", "mimic", "dynamics", "safety_controller"):
            child = joint.find(tag)
            if child is not None:
                joint.remove(child)

    if any(link.get("name") == "tcp_link" for link in arm_root.findall("link")):
        raise ValueError("Input model already contains tcp_link")

    ET.SubElement(arm_root, "link", {"name": "tcp_link"})
    tcp_joint = ET.SubElement(
        arm_root,
        "joint",
        {"name": "gripper_tcp_joint", "type": "fixed"},
    )
    ET.SubElement(
        tcp_joint,
        "origin",
        {"xyz": _vec3(tcp_xyz), "rpy": _vec3(tcp_rpy)},
    )
    ET.SubElement(tcp_joint, "parent", {"link": "gripper_base"})
    ET.SubElement(tcp_joint, "child", {"link": "tcp_link"})

    arm_root.insert(
        0,
        ET.Comment(
            "Generated by piper_x/build_gripper_dynamics_urdf.py; "
            "do not edit manually."
        ),
    )
    ET.indent(arm_root, space="  ")
    output.parent.mkdir(parents=True, exist_ok=True)
    ET.ElementTree(arm_root).write(output, encoding="utf-8", xml_declaration=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--arm-urdf", type=Path, default=DEFAULT_ARM_URDF)
    parser.add_argument("--gripper-xacro", type=Path, default=DEFAULT_GRIPPER_XACRO)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--tcp-xyz",
        type=float,
        nargs=3,
        default=[0.0, 0.0, 0.138],
        metavar=("X", "Y", "Z"),
        help="TCP translation in gripper_base coordinates, metres",
    )
    parser.add_argument(
        "--tcp-rpy",
        type=float,
        nargs=3,
        default=[0.0, 0.0, 0.0],
        metavar=("R", "P", "Y"),
        help="TCP orientation in gripper_base coordinates, radians",
    )
    args = parser.parse_args()
    build_model(
        arm_urdf=args.arm_urdf.resolve(),
        gripper_xacro=args.gripper_xacro.resolve(),
        output=args.output.resolve(),
        tcp_xyz=args.tcp_xyz,
        tcp_rpy=args.tcp_rpy,
    )
    print(f"Wrote {args.output.resolve()}")


if __name__ == "__main__":
    main()
